# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: chatter
  namespace: default
spec:
  selector:
    app: chatter
  type: NodePort
  ports:
    - name: chatter
      protocol: TCP
      port: 8000
      targetPort: 8000
