# Generated by Django 5.0.1 on 2024-01-08 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="connected_users",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="user_one",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_one",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="user_two",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_two",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
